# Top of file
# Common config
executors:
  my-go-executor:
    docker:
      - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/Static-Void-Academy/circleci-hello
commands:
  get-go-deps:
    description: Get go modules / dependencies
    steps:
      - run: go get -d ./...
version: 2.1 # !!!! IMPORTANT !!!! MUST USE 2.1 CONFIG
workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
jobs:
  build:
    executor: my-go-executor
    steps:
      - checkout
      - get-go-deps         # See common
      - run:
          name: Build the executable
          command: |
            echo "Other important command here as example"
            go build ./src/app
      - persist_to_workspace:
          root: .
          paths: ./*
      - store_artifacts:
          path: ./circleci-hello
  test:
    executor: my-go-executor
    steps:
      - attach_workspace:
          at: .
      - checkout
      - get-go-deps         # See common
      - run: go test ./src/app